#!/bin/zsh
# I'm not sure if this level of scuffed directory traversal is okay... eh whatever.
\cp $GIT_DIR/../../../../nvim/vim-plug/plug.vim $GIT_DIR/../../../../nvim/.local/share/nvim/site/autoload/plug.vim
echo "[VIM-PLUG] Updated `cd $GIT_DIR/../../../..; pwd`/nvim/.local/share/nvim/site/autoload/plug.vim"
# --- Finished
exit 0
