format = """
[┌ ](fg:#757575)\
[$username$hostname ](#345B9A)\
[](#9A348E)\
$directory\
${custom.git}\
$git_branch\
$git_status\
$container
[└ ](fg:#757575)\
$status\
$character
"""

#right_format = """[$c$golang$haskell$java$rust](#86BBD8)"""
right_format = """$cmd_duration"""

[character]
success_symbol = "[\\$](fg:#FFFFFF)"
error_symbol = "[\\$](bold red)"

[status]
disabled = false
map_symbol = true
pipestatus = true
pipestatus_format = "[[$status](bg:#CC3300)](fg:#CC3300) -> [[$status](bg:#CC3300)](fg:#CC3300) "
symbol = ""
signal_symbol = ""
sigint_symbol = ""
# This is a hack that requires modifying the source to match 'common_meaning'
error_symbol = " "
access_symbol = " "
not_executable_symbol = " "
not_found_symbol = " "

format = "[[$common_meaning$symbol$status](bg:#CC3300)](fg:#CC3300) "

[username]
show_always = true
format = '$user'

[hostname]
format = '@$hostname'

[directory]
format = "[$path](bg:#9A348E)"
truncation_length = 1

[custom.git]
when = 'if [ -d .git ]; then false; elif git rev-parse --is-inside-work-tree; then false; else; true; fi'
format = '[](#9A348E)'

[git_branch]
symbol = ""
format = '[ ](bg:#9A348E)[](bg:#26605B fg:#9A348E)[ $symbol $branch ](bg:#26605B)'

[git_status]
ahead = "(⇡$count) "
behind = "(⇣$count) "
diverged = "(⇡$count/⇣$count) "

up_to_date = " "
staged = "[+$count](fg:#5af78d bg:#26605B) "
deleted = "[-$count](fg:#ff5b56 bg:#26605B) "
modified = "[~$count](fg:#F4F8A8 bg:#26605B) "
untracked = "[?$count](fg:#ABABAB bg:#26605B) "
conflicted = "[!](fg:#ff6700 bg:#26605B) "
stashed = "*"

ignore_submodules = true
format = '[($conflicted$ahead_behind$untracked$staged$modified$deleted$stashed$up_to_date)](bg:#26605B)[](fg:#26605B)'

[cmd_duration]
min_time = 60_000
format = '[$duration](yellow)'

# all unused
[c]
symbol = " "
format = '[$symbol ($version)](bg:#86BBD8)'

[golang]
symbol = " "
format = '[$symbol ($version)](bg:#86BBD8)'

[haskell]
symbol = " "
format = '[$symbol ($version)](bg:#86BBD8)'

[java]
symbol = " "
format = '[$symbol ($version)](bg:#86BBD8)'

[rust]
symbol = ""
format = '[$symbol ($version)](bg:#86BBD8)'

[container]
symbol = ""
format = '[ via $symbol](cyan)'

[time]
disabled = true 
time_format = "%R" # Hour:Minute Format
format = '[[ ♥ $time ](bg:#33658A)]($style)'
