#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_shadow                on
#yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  12
yabai -m config bottom_padding               12
yabai -m config left_padding                 12
yabai -m config right_padding                12
yabai -m config window_gap                   06

# application exemptions
yabai -m rule --add app="^GIMP" manage=off
yabai -m rule --add app="^TI-Nspire" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Da Vinci" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^OmniDiskSweeper$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Font Book$" manage=off
yabai -m rule --add app="^Calendar$" title="^$" manage=off # ignore popups
yabai -m rule --add app="^Ghidra" manage=off
yabai -m rule --add app="^QuickTime" manage=off
yabai -m rule --add app="^Skim$" manage=on

# min-width bullshittery
# basically, whenever we detect that a min-width app (prime suspects being Electron apps like Spotify and Discord), we send a command to resize (one of) the other windows. I'm an idiot and I suck at shell scripting, so it will only work if there are 2 windows. Also god forbid you try to call this with 2 min-width windows...
# ok, I need to figure out how to actually calculate the resize.
# ~~IF SPOTIFY IS ON THE RIGHT~~: --resize abs:<min-width>:<HEIGHT_CONSTANT>
# problem only occurs if spotify is on the right
# events of interest:
# -window_created
# -display_resized
# -
yabai -m signal --add app="^Spotify$" event=window_created action="echo \$YABAI_WINDOW_ID >> ~/Downloads/yabai-testing.txt" 

echo "yabai configuration loaded..."
